### ISSUE TITLE
Create repos, milestones, issues, and project board

### ISSUE THREAD

**Issue by allison-blumenthal** [allison-blumenthal/studio-star-client#4]
- [x] Create both repositories
- [x] Create milestones for each segment and entity
- [x] Write issue tickets for frontend and backend tasks for MVP
- [x] Create projects board for all issues
